### ISSUE TITLE
lsusb regexes fail on Python 3

### ISSUE THREAD

**Issue by jeremyvisser** [projecthorus/radiosonde_auto_rx#107]
When launching auto_rx with a default config on Python 3.7.2 on Arch Linux, I got this error in the logs:

```
ERROR:Config - Error parsing SDR 1 config - cannot use a string pattern on a bytes-like object
```

Unfortunately, this was fairly unhelpful, so I had to change the exception handler printing that log message to re-raise the exception (`s/continue/raise/`), which produced this more helpful traceback:

```
Traceback (most recent call last):
  File "auto_rx/autorx/config.py", line 263, in read_auto_rx_config
    _sdr_valid = rtlsdr_test(_device_idx)
  File "auto_rx/autorx/utils.py", line 558, in rtlsdr_test
    _rtl_exists = find_rtlsdr(device_idx)
  File "auto_rx/autorx/utils.py", line 470, in find_rtlsdr
    lsusb_info = lsusb()
  File "auto_rx/autorx/utils.py", line 359, in lsusb
    m = _LSUSB_BUS_DEVICE_RE.match(line)
TypeError: cannot use a string pattern on a bytes-like object
```

This seems to be related to the regexes in auto_rx/utils.py:

```
# Regexes to help parse lsusb's output
_INDENTATION_RE = re.compile(r'^( *)')
_LSUSB_BUS_DEVICE_RE = re.compile(r'^Bus (\d{3}) Device (\d{3}):')
_LSUSB_ENTRY_RE = re.compile(r'^ *([^ ]+) +([^ ]+) *([^ ].*)?$')
_LSUSB_GROUP_RE = re.compile(r'^ *([^ ]+.*):$')
```

If I change them to byte regexes, e.g.:

```
_LSUSB_BUS_DEVICE_RE = re.compile(b'^Bus (\d{3}) Device (\d{3}):')
```

Then the code runs, but it fails to detect my SDR. With either the default `device_idx = 0` or changing to `device_idx = 00000001` (matching what `/usr/bin/rtl_test` reports), it's not detected:

```
$ python3 auto_rx.py 
INFO:Reading configuration file...
ERROR:RTLSDR - RTLSDR with serial #00000001 is not present!
WARNING:Config - SDR #00000001 invalid.
ERROR:Config - No working SDRs! Cannot run...
CRITICAL:Error in configuration file! Exiting...
```

But with Python 2, it is detected fine:

```
$ python2 auto_rx.py                                                                                                               
INFO:Reading configuration file...
INFO:Config - Tested SDR #00000001 OK
 * Serving Flask app "autorx.web" (lazy loading)
 * Environment: production
[...]
```

Though I haven't confirmed it, I suspect the failure to detect the SDR is also a lsusb regex issue.

**Comment by darksidelemm** [comment]
Resolved by https://github.com/projecthorus/radiosonde_auto_rx/pull/138
