### ISSUE TITLE
Better handling of missing station.cfg

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/radiosonde_auto_rx#265]
At the moment, if you start auto_rx with station.cfg missing, you get the following error:
`2020-02-28 12:24:59,781 INFO:Reading configuration file...
Traceback (most recent call last):
  File "/Users/darkside/Dev/radiosonde_auto_rx/auto_rx/autorx/config.py", line 154, in read_auto_rx_config
    auto_rx_config['per_sonde_log'] = config.getboolean('logging', 'per_sonde_log')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
NoSectionError: No section: 'logging'
2020-02-28 12:24:59,782 ERROR:Could not parse config file.
2020-02-28 12:24:59,782 CRITICAL:Error in configuration file! Exiting...`

This is not particularly clear. A check should be added to confirm the file exists before attempting to read it.

**Comment by darksidelemm** [comment]
Fixed in the testing branch, will be merged into master once some real-world testing has been done.
