### ISSUE TITLE
KeyError: Session is disconnected

### ISSUE THREAD

**Issue by fkemps** [projecthorus/radiosonde_auto_rx#394]
Hello,

With this post I want to feedback a Tracebacks I get now and then on "Version - Local Version: 1.4.1-beta11".

Headless server: `49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 (Ubuntu 5.8.0-43.49~20.04.1-generic 5.8.18)`

```
feb 26 07:29:22 spy auto_rx[312116]: 2021-02-26 07:29:22,758 INFO:Flask - New Web Client connected!
feb 26 07:29:36 spy auto_rx[312116]: 2021-02-26 07:29:36,591 INFO:Scanner #0 - Running frequency scan.
feb 26 07:29:57 spy auto_rx[312116]: 2021-02-26 07:29:57,208 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:30:02 spy auto_rx[312116]: 2021-02-26 07:30:02,075 ERROR:Error on request:
feb 26 07:30:02 spy auto_rx[312116]: Traceback (most recent call last):
feb 26 07:30:02 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
feb 26 07:30:02 spy auto_rx[312116]:     execute(self.server.app)
feb 26 07:30:02 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
feb 26 07:30:02 spy auto_rx[312116]:     application_iter = app(environ, start_response)
feb 26 07:30:02 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
feb 26 07:30:02 spy auto_rx[312116]:     return self.wsgi_app(environ, start_response)
feb 26 07:30:02 spy auto_rx[312116]:   File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 45, in __call__
feb 26 07:30:02 spy auto_rx[312116]:     return super(_SocketIOMiddleware, self).__call__(environ,
feb 26 07:30:02 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
feb 26 07:30:02 spy auto_rx[312116]:     return self.engineio_app.handle_request(environ, start_response)
feb 26 07:30:02 spy auto_rx[312116]:   File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 563, in handle_request
feb 26 07:30:02 spy auto_rx[312116]:     return self.eio.handle_request(environ, start_response)
feb 26 07:30:02 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/server.py", line 396, in handle_request
feb 26 07:30:02 spy auto_rx[312116]:     socket = self._get_socket(sid)
feb 26 07:30:02 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/server.py", line 609, in _get_socket
feb 26 07:30:02 spy auto_rx[312116]:     raise KeyError('Session is disconnected')
feb 26 07:30:02 spy auto_rx[312116]: KeyError: 'Session is disconnected'
feb 26 07:30:22 spy auto_rx[312116]: 2021-02-26 07:30:22,845 INFO:Scanner #0 - Running frequency scan.
feb 26 07:30:32 spy auto_rx[312116]: 2021-02-26 07:30:32,629 INFO:Flask - New Web Client connected!
feb 26 07:30:43 spy auto_rx[312116]: 2021-02-26 07:30:43,191 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:31:08 spy auto_rx[312116]: 2021-02-26 07:31:08,853 INFO:Scanner #0 - Running frequency scan.
feb 26 07:31:29 spy auto_rx[312116]: 2021-02-26 07:31:29,225 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:31:29 spy auto_rx[312116]: 2021-02-26 07:31:29,464 ERROR:Error on request:
feb 26 07:31:29 spy auto_rx[312116]: Traceback (most recent call last):
feb 26 07:31:29 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
feb 26 07:31:29 spy auto_rx[312116]:     execute(self.server.app)
feb 26 07:31:29 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
feb 26 07:31:29 spy auto_rx[312116]:     application_iter = app(environ, start_response)
feb 26 07:31:29 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
feb 26 07:31:29 spy auto_rx[312116]:     return self.wsgi_app(environ, start_response)
feb 26 07:31:29 spy auto_rx[312116]:   File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 45, in __call__
feb 26 07:31:29 spy auto_rx[312116]:     return super(_SocketIOMiddleware, self).__call__(environ,
feb 26 07:31:29 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
feb 26 07:31:29 spy auto_rx[312116]:     return self.engineio_app.handle_request(environ, start_response)
feb 26 07:31:29 spy auto_rx[312116]:   File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 563, in handle_request
feb 26 07:31:29 spy auto_rx[312116]:     return self.eio.handle_request(environ, start_response)
feb 26 07:31:29 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/server.py", line 396, in handle_request
feb 26 07:31:29 spy auto_rx[312116]:     socket = self._get_socket(sid)
feb 26 07:31:29 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/server.py", line 609, in _get_socket
feb 26 07:31:29 spy auto_rx[312116]:     raise KeyError('Session is disconnected')
feb 26 07:31:29 spy auto_rx[312116]: KeyError: 'Session is disconnected'
feb 26 07:31:54 spy auto_rx[312116]: 2021-02-26 07:31:54,873 INFO:Scanner #0 - Running frequency scan.
feb 26 07:32:15 spy auto_rx[312116]: 2021-02-26 07:32:15,159 INFO:Scanner #0 - Detected peaks on 3 frequencies (MHz): [403.2 405.  402. ]
feb 26 07:32:15 spy auto_rx[312116]: 2021-02-26 07:32:15,209 INFO:Flask - New Web Client connected!
feb 26 07:32:48 spy auto_rx[312116]: 2021-02-26 07:32:48,645 INFO:Scanner #0 - Running frequency scan.
feb 26 07:33:09 spy auto_rx[312116]: 2021-02-26 07:33:09,227 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:33:34 spy auto_rx[312116]: 2021-02-26 07:33:34,848 INFO:Scanner #0 - Running frequency scan.
feb 26 07:33:54 spy auto_rx[312116]: 2021-02-26 07:33:54,350 INFO:Flask - New Web Client connected!
feb 26 07:33:55 spy auto_rx[312116]: 2021-02-26 07:33:55,090 INFO:Scanner #0 - Detected peaks on 3 frequencies (MHz): [403.2 402.  405. ]
feb 26 07:34:28 spy auto_rx[312116]: 2021-02-26 07:34:28,563 INFO:Scanner #0 - Running frequency scan.
feb 26 07:34:49 spy auto_rx[312116]: 2021-02-26 07:34:49,176 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:34:51 spy auto_rx[312116]: 2021-02-26 07:34:51,391 ERROR:Error on request:
feb 26 07:34:51 spy auto_rx[312116]: Traceback (most recent call last):
feb 26 07:34:51 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
feb 26 07:34:51 spy auto_rx[312116]:     execute(self.server.app)
feb 26 07:34:51 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
feb 26 07:34:51 spy auto_rx[312116]:     application_iter = app(environ, start_response)
feb 26 07:34:51 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
feb 26 07:34:51 spy auto_rx[312116]:     return self.wsgi_app(environ, start_response)
feb 26 07:34:51 spy auto_rx[312116]:   File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 45, in __call__
feb 26 07:34:51 spy auto_rx[312116]:     return super(_SocketIOMiddleware, self).__call__(environ,
feb 26 07:34:51 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
feb 26 07:34:51 spy auto_rx[312116]:     return self.engineio_app.handle_request(environ, start_response)
feb 26 07:34:51 spy auto_rx[312116]:   File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 563, in handle_request
feb 26 07:34:51 spy auto_rx[312116]:     return self.eio.handle_request(environ, start_response)
feb 26 07:34:51 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/server.py", line 396, in handle_request
feb 26 07:34:51 spy auto_rx[312116]:     socket = self._get_socket(sid)
feb 26 07:34:51 spy auto_rx[312116]:   File "/home/xxxxx/.local/lib/python3.8/site-packages/engineio/server.py", line 609, in _get_socket
feb 26 07:34:51 spy auto_rx[312116]:     raise KeyError('Session is disconnected')
feb 26 07:34:51 spy auto_rx[312116]: KeyError: 'Session is disconnected'
feb 26 07:35:14 spy auto_rx[312116]: 2021-02-26 07:35:14,825 INFO:Scanner #0 - Running frequency scan.
feb 26 07:35:35 spy auto_rx[312116]: 2021-02-26 07:35:35,218 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:36:00 spy auto_rx[312116]: 2021-02-26 07:36:00,852 INFO:Scanner #0 - Running frequency scan.
feb 26 07:36:21 spy auto_rx[312116]: 2021-02-26 07:36:21,203 INFO:Scanner #0 - Detected peaks on 2 frequencies (MHz): [403.2 402. ]
feb 26 07:36:46 spy auto_rx[312116]: 2021-02-26 07:36:46,858 INFO:Scanner #0 - Running frequency scan.
```

**Comment by darksidelemm** [comment]
This is just your web interface disconnecting. I probably need to figure out a way of inhibiting these errors...
