### ISSUE TITLE
log file directory permissions on new build

### ISSUE THREAD

**Issue by vk4tec** [projecthorus/radiosonde_auto_rx#57]
Apr 05 05:48:17 VK4TEC_HOME systemd[1]: auto_rx.service: Service hold-off time over, scheduling restart.
Apr 05 05:48:17 VK4TEC_HOME systemd[1]: Stopped auto_rx.
Apr 05 05:48:17 VK4TEC_HOME systemd[1]: Started auto_rx.
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]: Traceback (most recent call last):
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:   File "/home/pi/radiosonde_auto_rx/auto_rx/auto_rx.py", line 881, in <module>
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:     logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', filename=datetime.datetime.utcnow().strftime("log/%Y%m%d-%H%M%S_system.log"), level=logging_level)
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:   File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:     hdlr = FileHandler(filename, mode)
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:     StreamHandler.__init__(self, self._open())
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]:     stream = open(self.baseFilename, self.mode)
Apr 05 05:48:17 VK4TEC_HOME auto_rx[3347]: IOError: [Errno 13] Permission denied: '/home/pi/radiosonde_auto_rx/auto_rx/log/20180405-054817_system.log'
Apr 05 05:48:17 VK4TEC_HOME systemd[1]: auto_rx.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 05:48:17 VK4TEC_HOME systemd[1]: auto_rx.service: Unit entered failed state.
Apr 05 05:48:17 VK4TEC_HOME systemd[1]: auto_rx.service: Failed with result 'exit-code'.
Apr 05 05:48:20 VK4TEC_HOME systemd[1]: auto_rx.service: Service hold-off time over, scheduling restart.
Apr 05 05:48:20 VK4TEC_HOME systemd[1]: Stopped auto_rx.
Apr 05 05:48:20 VK4TEC_HOME systemd[1]: Started auto_rx.
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]: Traceback (most recent call last):
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:   File "/home/pi/radiosonde_auto_rx/auto_rx/auto_rx.py", line 881, in <module>
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:     logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', filename=datetime.datetime.utcnow().strftime("log/%Y%m%d-%H%M%S_system.log"), level=logging_level)
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:   File "/usr/lib/python2.7/logging/__init__.py", line 1547, in basicConfig
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:     hdlr = FileHandler(filename, mode)
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:     StreamHandler.__init__(self, self._open())
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]:     stream = open(self.baseFilename, self.mode)
Apr 05 05:48:21 VK4TEC_HOME auto_rx[3357]: IOError: [Errno 13] Permission denied: '/home/pi/radiosonde_auto_rx/auto_rx/log/20180405-054821_system.log'
Apr 05 05:48:21 VK4TEC_HOME systemd[1]: auto_rx.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 05:48:21 VK4TEC_HOME systemd[1]: auto_rx.service: Unit entered failed state.
Apr 05 05:48:21 VK4TEC_HOME systemd[1]: auto_rx.service: Failed with result 'exit-code'.

**Comment by vk4tec** [comment]
sudo chmod 777 /home/pi/radiosonde_auto_rx/log fixed it 

Also please see

http://59.167.159.165/system_logs/20180405-055119_system.log

log_power.csv failed to read

**Comment by vk4tec** [comment]
Installed as root instead of pi
